# Generated by Django 5.0.7 on 2024-08-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='card_cvv',
            field=models.CharField(max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='card_expiry',
            field=models.CharField(max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='card_number',
            field=models.CharField(max_length=16),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='card_cvv',
            field=models.CharField(max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='card_expiry',
            field=models.CharField(max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='card_number',
            field=models.CharField(max_length=16),
            preserve_default=False,
        ),
    ]
